package Digital;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author melatonind
 */
public class BitAdderCircuit extends javax.swing.JPanel {

    /**
     * Creates new form BitAdderCircuit
     */
    public BitAdderCircuit() {
        initComponents();
    }

    public Pin getPin1() {
        return pin1;
    }

    public Pin getPin2() {
        return pin2;
    }

    public Pin getPin3() {
        return pin3;
    }

    public Pin getPin4() {
        return pin4;
    }

    public Pin getPin5() {
        return pin5;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        circuitBoard1 = new Digital.CircuitBoard();
        pin1 = new Digital.Pin();
        pin2 = new Digital.Pin();
        pin3 = new Digital.Pin();
        xORGate1 = new Digital.XORGate();
        xORGate2 = new Digital.XORGate();
        aNDGate1 = new Digital.ANDGate();
        aNDGate2 = new Digital.ANDGate();
        oRGate1 = new Digital.ORGate();
        pin4 = new Digital.Pin();
        pin5 = new Digital.Pin();

        javax.swing.GroupLayout pin1Layout = new javax.swing.GroupLayout(pin1);
        pin1.setLayout(pin1Layout);
        pin1Layout.setHorizontalGroup(
            pin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pin1Layout.setVerticalGroup(
            pin1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pin2Layout = new javax.swing.GroupLayout(pin2);
        pin2.setLayout(pin2Layout);
        pin2Layout.setHorizontalGroup(
            pin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pin2Layout.setVerticalGroup(
            pin2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pin3Layout = new javax.swing.GroupLayout(pin3);
        pin3.setLayout(pin3Layout);
        pin3Layout.setHorizontalGroup(
            pin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pin3Layout.setVerticalGroup(
            pin3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        xORGate1.setInput0(pin1.getOutput());
        xORGate1.setInput1(pin2.getOutput());

        javax.swing.GroupLayout xORGate1Layout = new javax.swing.GroupLayout(xORGate1);
        xORGate1.setLayout(xORGate1Layout);
        xORGate1Layout.setHorizontalGroup(
            xORGate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        xORGate1Layout.setVerticalGroup(
            xORGate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        xORGate2.setInput0(xORGate1.getOutput());
        xORGate2.setInput1(pin3.getOutput());

        javax.swing.GroupLayout xORGate2Layout = new javax.swing.GroupLayout(xORGate2);
        xORGate2.setLayout(xORGate2Layout);
        xORGate2Layout.setHorizontalGroup(
            xORGate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        xORGate2Layout.setVerticalGroup(
            xORGate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        aNDGate1.setInput0(xORGate1.getOutput());
        aNDGate1.setInput1(pin3.getOutput());

        javax.swing.GroupLayout aNDGate1Layout = new javax.swing.GroupLayout(aNDGate1);
        aNDGate1.setLayout(aNDGate1Layout);
        aNDGate1Layout.setHorizontalGroup(
            aNDGate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        aNDGate1Layout.setVerticalGroup(
            aNDGate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        aNDGate2.setInput0(pin1.getOutput());
        aNDGate2.setInput1(pin2.getOutput());

        javax.swing.GroupLayout aNDGate2Layout = new javax.swing.GroupLayout(aNDGate2);
        aNDGate2.setLayout(aNDGate2Layout);
        aNDGate2Layout.setHorizontalGroup(
            aNDGate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        aNDGate2Layout.setVerticalGroup(
            aNDGate2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        oRGate1.setInput0(aNDGate1.getOutput());
        oRGate1.setInput1(aNDGate2.getOutput());

        javax.swing.GroupLayout oRGate1Layout = new javax.swing.GroupLayout(oRGate1);
        oRGate1.setLayout(oRGate1Layout);
        oRGate1Layout.setHorizontalGroup(
            oRGate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 48, Short.MAX_VALUE)
        );
        oRGate1Layout.setVerticalGroup(
            oRGate1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pin4.setInput0(xORGate2.getOutput());

        javax.swing.GroupLayout pin4Layout = new javax.swing.GroupLayout(pin4);
        pin4.setLayout(pin4Layout);
        pin4Layout.setHorizontalGroup(
            pin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pin4Layout.setVerticalGroup(
            pin4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        pin5.setInput0(oRGate1.getOutput());

        javax.swing.GroupLayout pin5Layout = new javax.swing.GroupLayout(pin5);
        pin5.setLayout(pin5Layout);
        pin5Layout.setHorizontalGroup(
            pin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        pin5Layout.setVerticalGroup(
            pin5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout circuitBoard1Layout = new javax.swing.GroupLayout(circuitBoard1);
        circuitBoard1.setLayout(circuitBoard1Layout);
        circuitBoard1Layout.setHorizontalGroup(
            circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circuitBoard1Layout.createSequentialGroup()
                .addGroup(circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(circuitBoard1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addGroup(circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(circuitBoard1Layout.createSequentialGroup()
                                    .addComponent(pin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(142, 142, 142)
                                    .addGroup(circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(aNDGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(aNDGate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(circuitBoard1Layout.createSequentialGroup()
                                            .addComponent(xORGate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(158, 158, 158)
                                            .addGroup(circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(pin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(pin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(circuitBoard1Layout.createSequentialGroup()
                                    .addComponent(pin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(oRGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(52, 52, 52)))))
                    .addGroup(circuitBoard1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(xORGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        circuitBoard1Layout.setVerticalGroup(
            circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(circuitBoard1Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pin4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xORGate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(xORGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(aNDGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(circuitBoard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oRGate1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pin5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(aNDGate2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pin3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(circuitBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(circuitBoard1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Digital.ANDGate aNDGate1;
    private Digital.ANDGate aNDGate2;
    private Digital.CircuitBoard circuitBoard1;
    private Digital.ORGate oRGate1;
    private Digital.Pin pin1;
    private Digital.Pin pin2;
    private Digital.Pin pin3;
    private Digital.Pin pin4;
    private Digital.Pin pin5;
    private Digital.XORGate xORGate1;
    private Digital.XORGate xORGate2;
    // End of variables declaration//GEN-END:variables
}
